# Generated by Django 5.2.6 on 2025-09-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
    ]
