# Generated by Django 5.2.6 on 2025-09-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_auto_20250917_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgproducto',
            name='url',
            field=models.ImageField(upload_to='watches/'),
        ),
    ]
