# Generated by Django 5.2.6 on 2025-09-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_alter_imgproducto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_exclusivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Deportivo', 'Deportivo'), ('Clasico', 'Clasico'), ('Elegante', 'Elegante'), ('Vintage', 'Vintage')], max_length=60, null=True),
        ),
    ]
