# Generated by Django 5.2.6 on 2025-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0008_alter_carrito_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='url_img_prod_devuelto',
            field=models.ImageField(blank=True, null=True, upload_to='devoluciones/'),
        ),
    ]
