# Generated by Django 5.2.6 on 2025-10-04 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0010_alter_resena_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
